# This is a basic workflow to help you get started with Actions

name: My LaTeX CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
      - "*"

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install Pygments

      - uses: xu-cheng/latex-action@v3
        with:
          # texlive_version: 2025
          latexmk_shell_escape: true
          work_in_root_file_dir: true
          root_file: 'Qual_Review/SM.tex'
          docker_image: texlive/texlive@sha256:b09360744230661858dc48526b9f20aa1269dba37d4e5310e3150b8f93584e58
          # pre_compile: |
          #   tlmgr install wrapfig enumitem titlesec svg physics biblatex biblatex-phys
          #   tlmgr install tocbibind siunitx cleveref transparent graphbox
          #   tlmgr install minted appendixnumberbeamer hyperref bbold

      - run : | 
            echo "Listing all files in the repository:"
            ls -alhtrR 

      - uses: actions/upload-artifact@v4
        with:
          name: my-slides
          path: 'Qual_Review/SM.pdf'


      - name: GH Release

        if: github.ref_type == 'tag'

        uses: softprops/action-gh-release@v2.2.2
        with:
          make_latest: true
          generate_release_notes: true
          files: 'Qual_Review/SM.pdf'